# Generated by Django 3.0.8 on 2020-07-11 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('middlename', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('genderField', models.CharField(choices=[(1, ' '), (2, 'Male'), (3, 'Female')], default='Null', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ushers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ushers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jiawem.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Singers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jiawem.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Pastors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('pastor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jiawem.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Deacon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deacon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jiawem.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jiawem.Person')),
            ],
        ),
    ]
