# Generated by Django 3.0.8 on 2020-07-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jiawem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='genderField',
            field=models.CharField(choices=[(1, ' '), (2, 'Male'), (3, 'Female')], default='null', max_length=6),
        ),
    ]
