# Generated by Django 3.0.8 on 2020-07-11 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jiawem', '0004_person_genderfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='genderField',
            field=models.CharField(choices=[('', ' '), ('', 'Male'), ('', 'Female')], default='null', max_length=6),
        ),
    ]
