# Generated by Django 3.0.8 on 2020-07-11 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jiawem', '0008_person_rolefield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='genderField',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='roleField',
            new_name='role',
        ),
    ]
