# Generated by Django 3.0.8 on 2020-07-11 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jiawem', '0011_singer_singer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='role',
        ),
    ]
